config/routes.rb
Rails.application.routes.draw do

  resources :appointments

  resources :diagnostics

  resources :physicians

  resources :patients

  resources :admin

  root 'dashboard#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :patient
  belongs_to :physician
  belongs_to :diagnostic

  def fee
    errors.add(:fee, "Should be at least 0.01.") if fee.nil? || fee < 0.01
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:date, :time, :reason, :fee, :note, :patient_id, :physician_id, :diagnostic_id)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date, :id => 'date' %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time, :id => 'time' %>
  </div>
  <div class="field">
    <%= f.label :patient_id %><br>
    <%= f.collection_select :patient_id, Patient.all, :id, :full_name %>
  </div>
  <div class="field">
    <%= f.label :physician_id %><br>
    <%= f.collection_select :physician_id, Physician.all, :id, :full_name %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_area :reason %>
  </div>

  <p>For staff to fill out only.</p>
  <div class="field">
    <%= f.label :fee %><br>
    <%= f.text_field :fee %>
  </div>
  <div class="field">
    <%= f.label :diagnostic_id %><br>
    <%= f.collection_select :diagnostic_id, Diagnostic.all, :id, :code %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h1>Listing Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Patient</th>
      <th>Physician</th>
      <th>Reason</th>
      <th>Fee</th>
      <th>Diagnostic</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.date %></td>
        <td><%= appointment.time %></td>
        <td><%= appointment.patient.full_name %></td>
        <td><%= appointment.physician.full_name %></td>
        <td><%= appointment.reason %></td>
        <td><%= number_to_currency(appointment.fee) %></td>
        <td><%= appointment.diagnostic_id %></td>
        <td><%= appointment.note %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @appointment.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @appointment.time %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @appointment.patient.full_name %>
</p>

<p>
  <strong>Physician:</strong>
  <%= @appointment.physician.full_name %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @appointment.reason %>
</p>

<p>
  <strong>Fee:</strong>
  <%= number_to_currency(@appointment.fee) %>
</p>

<p>
  <strong>Diagnostic Code:</strong>
  <%= @appointment.diagnostic.code %>
</p>

<p>
  <strong>Note:</strong>
  <%= @appointment.note %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>